# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Location(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, device: str=None, location: str=None, place: str=None):
        """
        Location - a model defined in Swagger

        :param device: The device of this Location.
        :type device: str
        :param location: The location of this Location.
        :type location: str
        :param place: The place of this Location.
        :type place: str
        """
        self.swagger_types = {
            'device': str,
            'location': str,
            'place': str
        }

        self.attribute_map = {
            'device': 'device',
            'location': 'location',
            'place': 'place'
        }

        self._device = device
        self._location = location
        self._place = place

    @classmethod
    def from_dict(cls, dikt) -> 'Location':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Location of this Location.
        :rtype: Location
        """
        return deserialize_model(dikt, cls)

    @property
    def device(self) -> str:
        """
        Gets the device of this Location.

        :return: The device of this Location.
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device: str):
        """
        Sets the device of this Location.

        :param device: The device of this Location.
        :type device: str
        """

        self._device = device

    @property
    def location(self) -> str:
        """
        Gets the location of this Location.

        :return: The location of this Location.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """
        Sets the location of this Location.

        :param location: The location of this Location.
        :type location: str
        """

        self._location = location

    @property
    def place(self) -> str:
        """
        Gets the place of this Location.

        :return: The place of this Location.
        :rtype: str
        """
        return self._place

    @place.setter
    def place(self, place: str):
        """
        Sets the place of this Location.

        :param place: The place of this Location.
        :type place: str
        """

        self._place = place

