# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ProjectsCollection(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, ids: List[int]=None):
        """
        ProjectsCollection - a model defined in Swagger

        :param ids: The ids of this ProjectsCollection.
        :type ids: List[int]
        """
        self.swagger_types = {
            'ids': List[int]
        }

        self.attribute_map = {
            'ids': 'ids'
        }

        self._ids = ids

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsCollection':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProjectsCollection of this ProjectsCollection.
        :rtype: ProjectsCollection
        """
        return deserialize_model(dikt, cls)

    @property
    def ids(self) -> List[int]:
        """
        Gets the ids of this ProjectsCollection.

        :return: The ids of this ProjectsCollection.
        :rtype: List[int]
        """
        return self._ids

    @ids.setter
    def ids(self, ids: List[int]):
        """
        Sets the ids of this ProjectsCollection.

        :param ids: The ids of this ProjectsCollection.
        :type ids: List[int]
        """

        self._ids = ids

