# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.inline_response2006_recordings import InlineResponse2006Recordings
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class RecordingsCollection(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, recordings: List[InlineResponse2006Recordings]=None):
        """
        RecordingsCollection - a model defined in Swagger

        :param recordings: The recordings of this RecordingsCollection.
        :type recordings: List[InlineResponse2006Recordings]
        """
        self.swagger_types = {
            'recordings': List[InlineResponse2006Recordings]
        }

        self.attribute_map = {
            'recordings': 'recordings'
        }

        self._recordings = recordings

    @classmethod
    def from_dict(cls, dikt) -> 'RecordingsCollection':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecordingsCollection of this RecordingsCollection.
        :rtype: RecordingsCollection
        """
        return deserialize_model(dikt, cls)

    @property
    def recordings(self) -> List[InlineResponse2006Recordings]:
        """
        Gets the recordings of this RecordingsCollection.

        :return: The recordings of this RecordingsCollection.
        :rtype: List[InlineResponse2006Recordings]
        """
        return self._recordings

    @recordings.setter
    def recordings(self, recordings: List[InlineResponse2006Recordings]):
        """
        Sets the recordings of this RecordingsCollection.

        :param recordings: The recordings of this RecordingsCollection.
        :type recordings: List[InlineResponse2006Recordings]
        """

        self._recordings = recordings

