# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ResponseEntity(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, body: object=None, status_code: str=None, status_code_value: int=None):
        """
        ResponseEntity - a model defined in Swagger

        :param body: The body of this ResponseEntity.
        :type body: object
        :param status_code: The status_code of this ResponseEntity.
        :type status_code: str
        :param status_code_value: The status_code_value of this ResponseEntity.
        :type status_code_value: int
        """
        self.swagger_types = {
            'body': object,
            'status_code': str,
            'status_code_value': int
        }

        self.attribute_map = {
            'body': 'body',
            'status_code': 'statusCode',
            'status_code_value': 'statusCodeValue'
        }

        self._body = body
        self._status_code = status_code
        self._status_code_value = status_code_value

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseEntity':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseEntity of this ResponseEntity.
        :rtype: ResponseEntity
        """
        return deserialize_model(dikt, cls)

    @property
    def body(self) -> object:
        """
        Gets the body of this ResponseEntity.

        :return: The body of this ResponseEntity.
        :rtype: object
        """
        return self._body

    @body.setter
    def body(self, body: object):
        """
        Sets the body of this ResponseEntity.

        :param body: The body of this ResponseEntity.
        :type body: object
        """

        self._body = body

    @property
    def status_code(self) -> str:
        """
        Gets the status_code of this ResponseEntity.

        :return: The status_code of this ResponseEntity.
        :rtype: str
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code: str):
        """
        Sets the status_code of this ResponseEntity.

        :param status_code: The status_code of this ResponseEntity.
        :type status_code: str
        """
        allowed_values = ["100", "101", "102", "103", "200", "201", "202", "203", "204", "205", "206", "207", "208", "226", "300", "301", "302", "303", "304", "305", "307", "308", "400", "401", "402", "403", "404", "405", "406", "407", "408", "409", "410", "411", "412", "413", "414", "415", "416", "417", "418", "419", "420", "421", "422", "423", "424", "426", "428", "429", "431", "451", "500", "501", "502", "503", "504", "505", "506", "507", "508", "509", "510", "511"]
        if status_code not in allowed_values:
            raise ValueError(
                "Invalid value for `status_code` ({0}), must be one of {1}"
                .format(status_code, allowed_values)
            )

        self._status_code = status_code

    @property
    def status_code_value(self) -> int:
        """
        Gets the status_code_value of this ResponseEntity.

        :return: The status_code_value of this ResponseEntity.
        :rtype: int
        """
        return self._status_code_value

    @status_code_value.setter
    def status_code_value(self, status_code_value: int):
        """
        Sets the status_code_value of this ResponseEntity.

        :param status_code_value: The status_code_value of this ResponseEntity.
        :type status_code_value: int
        """

        self._status_code_value = status_code_value

